# Generated by Django 2.2.4 on 2020-07-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Explog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shot', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=40)),
                ('context', models.TextField()),
                ('author', models.CharField(max_length=20)),
                ('edit_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
