# Generated by Django 2.2.4 on 2020-07-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explog',
            name='author',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='explog',
            name='shot',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='explog',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
