# Generated by Django 2.2.4 on 2020-07-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20200705_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explog',
            name='id',
        ),
        migrations.AlterField(
            model_name='explog',
            name='shot',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
